runtime: python36 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '{Password}'
  MYSQL_DB: 'Task Manager'
  MYSQL_HOST: '{IP Address}'

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles
