runtime: python36 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'root@123'
  MYSQL_DB: 'Task Manager'
  MYSQL_HOST: '192.168.0.33'

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles